name: 67a1e320-7c47-4ea9-8df8-e868326bc90b
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cf-units
  - copernicusmarine
  - ipykernel
  - jupyterlab
  - notebook=6
  - jupyter_server=1
  - libnetcdf
  - nbdime
  - netcdf4=1.6.0
  - pip
  - python<3.12
  - "tensorflow<2.16=cpu*"
  - pip:
      - ecmwflibs
      - icenet @ git+https://github.com/icenet-ai/icenet@0bac48fbc6447d937498b2c7240a2bd946430700
